# Dependency Review Configuration
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review

# Fail the action if any vulnerabilities are found with this severity or higher
fail-on-severity: moderate

# Allow or deny licenses
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - CC0-1.0
  - Unlicense

deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-1.0
  - AGPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0

# Fail if new packages with these licenses are introduced
license-check: true

# Fail if new vulnerabilities are introduced
vulnerability-check: true

# Comment configuration
comment-summary-in-pr: true